import pandas as pd
import fdb
import cx_Oracle
import sqlalchemy as sa
from sqlalchemy import create_engine
import datetime
from datetime import datetime, timedelta

def insert_log(p_inicio,p_resposta,p_texto):
    con2 = cx_Oracle.connect(user="DWU",password="3433cajubr4200", dsn="cajubr",encoding="UTF-8")
    cur2 = con2.cursor()
    chk = datetime.today()
    h_fim = chk.strftime('%d/%m/%Y %H:%M:%S')
    execucao = []
    execucao.append(p_inicio)
    execucao.append(h_fim)
    execucao.append(p_resposta)
    execucao.append(p_texto)
    cur2.execute("insert into VM_DETALHES_AGENT values (to_date(:1,'dd/mm/yyyy hh24:mi:ss'),to_date(:2,'dd/mm/yyyy hh24:mi:ss'),'00000096','ETL_PEDIDOS',:3,'',:4)",execucao)
    con2.commit()
    cur2.close()

now = datetime.today() - timedelta(days=365)
chk = datetime.today()
h_inicio = chk.strftime('%d/%m/%Y %H:%M:%S')
dt_referencia = now.strftime('%d.%m.%Y')
print('Periodo => '+dt_referencia)

conexao = fdb.connect(host='177.67.240.114',port=3055, database='E:/Sisplan/Base/14142F.fdb',user='sysdba', password='masterkey')
query = "WITH EXPEDIDO AS (SELECT CODIGO AS CODIGO,COR AS COR,NUMERO AS NUMERO,TAM AS TAM,SUM(PED.QTDE) AS QTDE FROM PEDIDO3_001 PED WHERE QTDE_F = 0 AND QTDE <> 0 GROUP BY CODIGO,COR,NUMERO,TAM) SELECT '' AS CD_EMPRESA,COALESCE(EMPRESA.EMP_PAT,'_001') AS CD_FILIAL,PED.NUMERO AS CD_PEDIDO,CAST(PED.DTDIGITA AS VARCHAR(10)) AS DT_DIGITACAO,CAST(PED.DT_EMISSAO AS VARCHAR(10)) AS DT_EMISSAO,PED.CODCLI AS CD_CLIENTE,PED.CODREP AS CD_REPRESENTANTE,ITEM.ID_ITEM_PED AS ID_ITEM_PEDIDO,ITEM.CODIGO AS CD_PRODUTO,ITEM.COR AS CD_COR,ITEM.TAM AS CD_TAMANHO,ITEM.ORDEM AS SEQ_ITEM,PED.COLECAO AS CD_COLECAO,PED.STATUS AS CD_STATUS,ITEM.QTDE_ORIG AS VL_QTDE_PEDIDO,ITEM.QTDE AS VL_QTDE_ABERTO,ITEM.QTDE_CANC AS VL_QTDE_CANCELADO,ITEM.QTDE_F AS VL_QTDE_FATURADO,ITEM.PRECO AS VL_PRECO_ITEM,cast( (ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3)) AS VL_TOTAL_PEDIDO,cast( ITEM.QTDE as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3)) AS VL_TOTAL_ABERTO,cast( ITEM.QTDE_CANC as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3))  AS VL_TOTAL_CANCELADO,cast(ITEM.QTDE_F as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3))  AS VL_TOTAL_FATURADO,PED.COM1 AS VL_PERC_COMISSAO,cast( (ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) as numeric(18,0)) * cast(ITEM.PRECO as numeric(18,3)) * cast(PED.COM1 as numeric(18,2)) / cast(100 as numeric(18,0)) AS VL_COMISSAO,PED.PER_DESC AS VL_PERC_DESCONTO,CAST((ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) AS NUMERIC(18,0))*CAST(ITEM.PRECO AS NUMERIC(18,3))*CAST(PED.PER_DESC AS NUMERIC(18,2))/CAST(100 AS NUMERIC(18,0)) AS VL_DESCONTO,PED.BONIFICACAO AS CD_BONIFICACAO,PED.MOTIVO AS CD_MOTIVO_CANCELAMENTO,CAST(PED.DT_CANC AS VARCHAR(10)) AS DT_CANCELAMENTO,PED.CIF AS CD_TP_FRETE,CAST(PED.ENTREGA AS VARCHAR(10)) AS DT_ENTREGA_PREV,PED.TAB_PRE AS CD_TABELA_PRECO,PED.MOEDA AS CD_MOEDA,PED.NOTA AS NUM_NOTA_FATURADA,PED.TIPO AS CD_TP_PEDIDO,PED.HISTORICO AS CD_HISTORICO,'' AS OBS,PED.PRZ_MEDIO AS VL_PRAZO_MEDIO,PED.ID_ENT AS ID_ENT,PED.ID_PED AS ID_PED,CAST(PED.DT_ORIG_ENTREGA AS VARCHAR(10)) AS DT_ORIG_ENTREGA,CAST(RE.QTDE AS VARCHAR(10)) AS QTD_RESERVADA, CAST(EX.QTDE AS VARCHAR(10)) AS QTD_EXPEDIDO, CAST(DT_FATURA AS VARCHAR(10)) AS DT_FATURA FROM PEDIDO_001 PED INNER JOIN PED_ITEN_001 ITEM ON (ITEM.ID_PED = PED.ID_PED) LEFT JOIN EMPRESA EMPRESA ON (EMPRESA.EMP_ID = PED.EMP_ID) LEFT JOIN (SELECT * FROM ped_reserva_001 PED WHERE QTDE_B = 0 AND QTDE <> 0) RE ON  (ITEM.CODIGO = RE.CODIGO) AND (ITEM.COR = RE.COR) AND (ITEM.NUMERO = RE.NUMERO) AND (ITEM.TAM = RE.TAM) LEFT JOIN EXPEDIDO EX ON  (ITEM.CODIGO = EX.CODIGO) AND (ITEM.COR = EX.COR) AND (ITEM.NUMERO = EX.NUMERO) AND (ITEM.TAM = EX.TAM) WHERE PED.DT_EMISSAO >= '"""+dt_referencia+chr(39)
#query = """WITH EXPEDIDO AS (SELECT CODIGO AS CODIGO,COR AS COR,NUMERO AS NUMERO,TAM AS TAM,SUM(PED.QTDE) AS QTDE FROM PEDIDO3_001 PED WHERE QTDE_F = 0 AND QTDE <> 0 GROUP BY CODIGO,COR,NUMERO,TAM)SELECT '' AS CD_EMPRESA,COALESCE(EMPRESA.EMP_PAT,'_001') AS CD_FILIAL,PED.NUMERO AS CD_PEDIDO,CAST(PED.DTDIGITA AS VARCHAR(10)) AS DT_DIGITACAO,CAST(PED.DT_EMISSAO AS VARCHAR(10)) AS DT_EMISSAO,PED.CODCLI AS CD_CLIENTE,PED.CODREP AS CD_REPRESENTANTE,ITEM.ID_ITEM_PED AS ID_ITEM_PEDIDO,ITEM.CODIGO AS CD_PRODUTO,ITEM.COR AS CD_COR,ITEM.TAM AS CD_TAMANHO,ITEM.ORDEM AS SEQ_ITEM,PED.COLECAO AS CD_COLECAO,PED.STATUS AS CD_STATUS,ITEM.QTDE_ORIG AS VL_QTDE_PEDIDO,ITEM.QTDE AS VL_QTDE_ABERTO,ITEM.QTDE_CANC AS VL_QTDE_CANCELADO,ITEM.QTDE_F AS VL_QTDE_FATURADO,ITEM.PRECO AS VL_PRECO_ITEM,cast( (ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3)) AS VL_TOTAL_PEDIDO,cast( ITEM.QTDE as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3)) AS VL_TOTAL_ABERTO,cast( ITEM.QTDE_CANC as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3))  AS VL_TOTAL_CANCELADO,cast(ITEM.QTDE_F as numeric(18,0)) * cast(ITEM.PRECO as NUMERIC(13,3))  AS VL_TOTAL_FATURADO,PED.COM1 AS VL_PERC_COMISSAO,cast( (ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) as numeric(18,0)) * cast(ITEM.PRECO as numeric(18,3)) * cast(PED.COM1 as numeric(18,2)) / cast(100 as numeric(18,0)) AS VL_COMISSAO,PED.PER_DESC AS VL_PERC_DESCONTO,CAST((ITEM.QTDE+ITEM.QTDE_CANC+ITEM.QTDE_F) AS NUMERIC(18,0))*CAST(ITEM.PRECO AS NUMERIC(18,3))*CAST(PED.PER_DESC AS NUMERIC(18,2))/CAST(100 AS NUMERIC(18,0)) AS VL_DESCONTO,PED.BONIFICACAO AS CD_BONIFICACAO,PED.MOTIVO AS CD_MOTIVO_CANCELAMENTO,CAST(PED.DT_CANC AS VARCHAR(10)) AS DT_CANCELAMENTO,PED.CIF AS CD_TP_FRETE,CAST(PED.ENTREGA AS VARCHAR(10)) AS DT_ENTREGA_PREV,PED.TAB_PRE AS CD_TABELA_PRECO,PED.MOEDA AS CD_MOEDA,PED.NOTA AS NUM_NOTA_FATURADA,PED.TIPO AS CD_TP_PEDIDO,PED.HISTORICO AS CD_HISTORICO,'' AS OBS,PED.PRZ_MEDIO AS VL_PRAZO_MEDIO,PED.ID_ENT AS ID_ENT,PED.ID_PED AS ID_PED,CAST(PED.DT_ORIG_ENTREGA AS VARCHAR(10)) AS DT_ORIG_ENTREGA,CAST(RE.QTDE AS VARCHAR(10)) AS QTD_RESERVADA, CAST(EX.QTDE AS VARCHAR(10)) AS QTD_EXPEDIDO FROM PEDIDO_001 PED INNER JOIN PED_ITEN_001 ITEM ON (ITEM.ID_PED = PED.ID_PED) LEFT JOIN EMPRESA EMPRESA ON (EMPRESA.EMP_ID = PED.EMP_ID) LEFT JOIN (SELECT * FROM ped_reserva_001 PED WHERE QTDE_B = 0 AND QTDE <> 0) RE ON  (ITEM.CODIGO = RE.CODIGO) AND (ITEM.COR = RE.COR) AND (ITEM.NUMERO = RE.NUMERO) AND (ITEM.TAM = RE.TAM) LEFT JOIN EXPEDIDO EX ON  (ITEM.CODIGO = EX.CODIGO) AND (ITEM.COR = EX.COR) AND (ITEM.NUMERO = EX.NUMERO) AND (ITEM.TAM = EX.TAM) WHERE PED.DT_EMISSAO >= '"""+dt_referencia+chr(39)

dsn = cx_Oracle.makedsn('cloud.upquery.com',port=1521,service_name='cajubr')
engine = create_engine('oracle+cx_oracle://%s:%s@%s' % ("DWU", "3433cajubr4200", dsn))

engine.fast_executemany = True

try:
    dados = pd.read_sql(query, con=conexao)

    object_columns = [c for c in dados.columns[dados.dtypes == 'object'].tolist()]
    dtyp = {c:sa.types.VARCHAR(dados[c].str.len().max()) for c in object_columns}

    dados['DT_EMISSAO'] = pd.to_datetime(dados['DT_EMISSAO'])

    con = cx_Oracle.connect(user="DWU",password="3433cajubr4200", dsn="cajubr",encoding="UTF-8")
    cur = con.cursor()

    deletar = []
    deletar.append(str(dt_referencia))
    cur.execute("delete DWU.ETL_PEDIDOS where dt_emissao >= :1", deletar)
    del_linhas = cur.rowcount
    print('Deleteadas: '+str(cur.rowcount))

    dados.to_sql(name="etl_pedidos",con=engine, if_exists='append', index=False, chunksize=50000,  dtype=dtyp)
    insert_linhas = len(dados)
    insert_log(h_inicio,'EXECUTADO OK','Deletadas: '+str(del_linhas)+' Inseridas: '+str(insert_linhas))
    con.commit()
    cur.close()

except Exception as e:
    insert_log(h_inicio,'Erro',e)


